python exercises week one
tianchi8i/python_exercises pull request #1
Opened 2022-02-13 21:58 UTC by tianchi8i

2022-02-14 01:03 UTC, ariel-yap requested changes
Please start documenting the code for these exercises so they are descriptive of what the script will do.

2022-02-14 01:03 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#1.py
> +#1
Please start documenting these with their respective exercise question in the format of [script docstrings](https://realpython.com/documenting-python-code/#script-docstrings). For example, this should have something along the lines of:
```
""" Week 1 - Exercise 1
This script takes a number n, prints i^2 for all non-negative numbers that are less than n, where i <= n.
This has the exception for i = 4 and will not print anything.
"""
```

2022-02-14 01:03 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#3.py
> +    z = a.count(b)
As discussed in one of our previous sessions, for the purpose of this exercise, please change this  to not use `str.count()`

2022-02-14 01:03 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#4.py
> +        #toilet paper,water
remove comments that are not helpful

2022-02-14 01:03 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#5.py
> +        #14,21,28
same here

2022-03-10 02:38 UTC, ariel-yap requested changes

2022-03-10 02:38 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#2.py
> +        x = " "
What happens if we change `s = "Tianchi!@#Ma"`?

2022-03-10 02:38 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#3.py
> +    It add one a number to 'count' every time the computer find c in a,
This doesn't quite make sense, as c is the length of the substring b

2022-03-10 02:38 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#1.py
> +""" Week 1 - Exercise 1
Only this file has this title, which is inconsistent to the rest, please add it to the rest of the script files

2022-03-13 23:03 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#1.py
> +""" Week 1 - Exercise 1
Scratch that, just remove this line from this file, and that will have everything else consistent.

2022-03-16 01:18 UTC, tianchi8i commented on Python Tutorial Exercises(Week 1)/#2.py
> +        x = " "
You will get `tIANCHIIIIImA`. It will repeat the last loop until it finds the next character. We can use 'else: continue' to fix that.

2022-03-16 01:54 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#2.py
> +        x = " "
Please implement the fix so that it works correctly, printing `tIANCHI!@#mA`

2022-03-16 02:27 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#3.py
> +    as c is the length of the substring b
This still doesn't make sense, you have just copy and pasted the PR comment?

2022-03-20 19:29 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#2.py
> +    elif i.isspace():
```
elif i.isspace():
   x = " "
else:
   x = i
```
Those two conditions do the same thing, you can just have the last else statement.

2022-03-20 19:30 UTC, ariel-yap commented on Python Tutorial Exercises(Week 1)/#3.py
> +    c = len(b) = 2 then use for loop and a[i:i+c] to check every 2 itemes/character(01,12,23,34...)
itemes -> items

2022-03-24 02:05 UTC, merged